# Generated by Django 6.1.1 on 2026-10-05 21:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_organizador_subtask_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.DecimalField(decimal_places=2, default=6, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('organizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limite_diario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
