# Generated by Django 6.1.1 on 2026-10-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_limite_diario'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='nota',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('hecha', 'Hecha'), ('pospuesta', 'Pospuesta')], default='pendiente', max_length=20),
        ),
    ]
