# Generated by Django 6.1.1 on 2026-10-10 18:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_subtask_nota_alter_subtask_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='horas_estimadas',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
